gaps/blueprint_api.py
import os.path
import random
from datetime import datetime
from typing import Dict

from flask import Blueprint, request, jsonify, current_app, abort, url_for
from werkzeug.datastructures import FileStorage
from werkzeug.utils import secure_filename

from gaps.gene_searcher import *
from gaps import file_reader as reader
from gaps.genelogic import GenepanelReader, DatabaseInserter, \
    GenepanelColumnNotFound

blueprint_api = Blueprint("blueprint_api", __name__)


def genes_box(searcher, valid_parameters):
    """
    Checks to include/ exlude genes symbols, and creates a set
    with the genes to include/ exlude, if a gene is in a set, the gene
    will be or won't be added to the database later in query_processor.py
    :param searcher: query_proccessor link to fill init variables
    :param valid_parameters: parameters with input from the user
    :return:
    """
    if valid_parameters["radio_include_symbols"] == "true":
        searcher.include_exclude = True
    else:
        searcher.include_exclude = False
    genes_list = list(valid_parameters["input_symbols"].split(","))
    set_genes_list = set()
    for gene in genes_list:
        set_genes_list.add(gene.strip())
    searcher.specific_gene_symbols = set_genes_list


@blueprint_api.route("/query_builder", methods=["POST"])
def query_builder_submit():
    """A function which handles POST-requests to the
       '/query_builder'-route. This route is used to
       inform the client about uploaded valid files,
       if the query has any results and to redirect
       the user to the results-page if there are
       results.

    :return JSON-response containing valid values (JSON).
    """
    secure_filenames = VerifyFormParameters.get_valid_filenames(
        "input_load_symbols")
    valid_parameters = VerifyFormParameters.get_valid_parameters()
    upload_path = current_app.config['UPLOAD_PATH']
    try:
        if secure_filenames:
            filenames = tuple(secure_filenames.keys())
            filename = filenames[0]
            file_location = os.path.join(upload_path, filename)
            secure_filenames[filename].save(file_location)
        searcher = GeneSearcher()
        # check dit met true of false
        # for the include / exclude, but currently disabled due to
        # issues with the database
        # if valid_parameters.get("input_symbols"):
        #     searcher.specify_gene = True
        #     genes_box(searcher, valid_parameters)
        # elif file_location and len(file_location) > 1:  # for the file input
        #     searcher.specify_gene = True  # use white/black list
        #     if valid_parameters["radio_include_symbols"] == "true":
        #         searcher.include_exclude = True
        #     else:
        #         searcher.include_exclude = False
        #     searcher.specific_gene_symbols = reader.file_reader(file_location)
        #
        #     print("Reading file")
        # elif file_location and len(file_location) > 1 and \
        #         valid_parameters.get("input_symbols"):
        #     print("komt die")
        #     searcher.specify_gene = True
        #     genes_box(searcher, valid_parameters)
        count = searcher.fetch_results(valid_parameters)
        if count < 1:
            response = {
                "message": "No articles found! Adjust your search parameters "
                           "and try again.",
                "type": "info"}
        else:
            searcher.results_query()
            response = {"redirect": url_for("blueprint_results.results",
                                            query_id=searcher.uuid_query)}
        return jsonify(response)
    except (NoQuerySpecified, NoDateAfterSpecified, NoDateBeforeSpecified,
            MalformedQuery, IncorrectArticleFound, NoGeneFound) as e:
        response = {"message": str(e),
                    "type": "warning"}
    finally:
        if secure_filenames:
            for filename in secure_filenames.keys():
                os.remove(os.path.join(upload_path, filename))
    return jsonify(response)


@blueprint_api.route("/update_genepanel", methods=["POST"])
def update_genepanel_submit():
    """A function which handles POST-requests to the
       '/update_genepanel'-route. This route is used
       to inform the client about valid uploaded
       files and what has changed after the update of
       a genepanel.

    :return JSON-response containing valid values (JSON).
    """
    secure_filenames = VerifyFormParameters.get_valid_filenames(
        "input_upload_genepanel")
    upload_path = current_app.config['UPLOAD_PATH']
    try:
        if secure_filenames:
            filenames = tuple(secure_filenames.keys())
            filename = filenames[0]
            file_location = os.path.join(upload_path, filename)
            secure_filenames[filename].save(file_location)
            genepanel_data = GenepanelReader(
                filename=file_location).get_genepanel_data()
            DatabaseInserter().insert_genepanel(genepanel_data)
            response = {
                "message": "Genepanels updated successfully! Refresh the "
                           "page to see the new statistics about "
                           "the updated geneanels.", "type": "success"}
        else:
            response = {
                "message": "No file uploaded! Could not update genepanels.",
                "type": "danger"}
    except GenepanelColumnNotFound as e:
        response = {"message": str(e),
                    "type": "danger"}
    finally:
        if secure_filenames:
            for filename in secure_filenames.keys():
                os.remove(os.path.join(upload_path, filename))
    return jsonify(response)


class VerifyFormParameters:
    """A class that extracts valid/secure variables and
       from requests so the server can safely process
       these variables and files.
    """

    @staticmethod
    def get_valid_filenames(file_upload_field: str) -> Dict[str, FileStorage]:
        """A method which secures filenames from requests
           and returns the secured filenames for safe
           storage and processing of the files.

        :param file_upload_field Field to check containing
                                 possible filenames (str).
        :return Secured filenames (Dict[str, FileStorage]).
        """
        if file_upload_field in request.files:
            uploaded_files = request.files.getlist(file_upload_field)
            filenames = dict()
            for uploaded_file in uploaded_files:
                if uploaded_file.filename != "":
                    file_extension = os.path.splitext(uploaded_file.filename)[
                        1]
                    if file_extension in current_app.config[
                        "UPLOAD_EXTENSIONS"]:
                        filename = secure_filename(uploaded_file.filename)
                        if filename != "":
                            filenames[
                                f"{random.randint(0, 9000)}_{filename}"] = uploaded_file
                    else:
                        abort(400)
            if len(filenames) > 0:
                return filenames

    @staticmethod
    def get_valid_parameters() -> Dict[str, str]:
        """A method which extracts all elements from a
           form that are not empty and returns them for
           further processing.

        :return All non-default values from the form
                (dict(str, str)).
        """
        verified_values = dict()
        for parameter_key in request.form.keys():
            submitted_value = request.form[parameter_key].strip()
            if submitted_value != "":
                if "date" in parameter_key:
                    submitted_value = datetime.strptime(submitted_value,
                                                        "%Y-%m-%d")
                verified_values[parameter_key] = submitted_value
        if len(verified_values) > 0:
            return verified_values

gaps/blueprint_help.py
from flask import Blueprint, render_template

blueprint_help = Blueprint("blueprint_help", __name__)


@blueprint_help.route("/help")
def route_help():
    """A function which handles requests to the '/help'-
       route for the webapp.

    :return Rendered template of 'template_help.html'.
    """
    return render_template("template_help.html", active_nav="help")

gaps/blueprint_homepage.py
from flask import Blueprint, redirect, url_for

blueprint_homepage = Blueprint("blueprint_homepage", __name__)


@blueprint_homepage.route("/")
def homepage():
    """A function which handles requests to the '/'-
       route for the webapp.

    :return Rendered template of 'template_homepage.html' (str).
    """
    return redirect(url_for("blueprint_query_builder.query_builder"))
    # search = request.args.get("search")
    # return render_template("template_query_builder.html", active="home", search=search)

# shift command r = hard refresh cache/ en zooi

gaps/blueprint_update_genepanel.py
from flask import Blueprint, render_template
from sqlalchemy.exc import OperationalError

from gaps.models import Gene, Alias, Genepanel

blueprint_update_genepanel = Blueprint("blueprint_update_genepanel", __name__)


@blueprint_update_genepanel.route("/update_genepanel")
def update_genepanel():
    """A function which handles requests for the '/update_genepanel'-
       route for the webapp.

    :return Rendered template of 'template_update_genepanel.html'.
    """
    try:
        genes = Gene.query.where(Gene.in_genepanel == True).count()
        aliases = Alias.query.count()
        genepanels = Genepanel.query.count()
        return render_template("template_update_genepanel.html",
                               active_nav="genepanel",
                               unique_genes=genes,
                               unique_aliases=aliases,
                               unique_genepanels=genepanels)
    except OperationalError:
        return render_template("template_update_genepanel.html",
                               active_nav="genepanel")

gaps/templates/base_template.html
<!DOCTYPE html>
<html id="page" lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet"
          href="{{ url_for("static", filename="bootstrap/css/bootstrap.min.css") }}">
    <link rel="stylesheet"
          href="{{ url_for("static", filename="css/styles.css") }}">
    <link rel="shortcut icon"
          href="{{ url_for('static', filename='logo_gaps.ico') }}">
    {% block head %}{% endblock %}
</head>

<body id="body">
<header id="header">
    <nav class="navbar navbar-dark navbar-expand-md" id="navigation_top">
        <div class="container-fluid"><a class="navbar-brand" id="app_name"
                                        href="{{ url_for('blueprint_homepage.homepage') }}">Gene
            App Scraper</a>
            <button data-bs-toggle="collapse"
                    class="navbar-toggler navbar-dark"
                    data-bs-target="#navigation_items_collapse"
                    id="hamburger_button"><span class="visually-hidden">Toggle navigation</span><span
                    class="navbar-toggler-icon" id="hamburger_icon"></span>
            </button>
            <div class="collapse navbar-collapse"
                 id="navigation_items_collapse">
                <ul class="navbar-nav" id="navigation_items">
                    <li class="nav-item" id="navigation_query"><a
                            class="nav-link {% if active_nav and active_nav == 'query' %}active{% endif %}"
                            id="link_query"
                            href="{{ url_for('blueprint_query_builder.query_builder') }}">Query_builder</a>
                    </li>
                        <li class="nav-item" id="navigation_history" hidden=""><a class="nav-link {% if active_nav and active_nav == 'history' %}active{% endif %}" id="link_history" href="#">Retrieve history</a></li>
                        <li class="nav-item" id="navigation_genepanel"><a class="nav-link {% if active_nav and active_nav == 'genepanel' %}active{% endif %}" id="link_genepanel" href="{{ url_for('blueprint_update_genepanel.update_genepanel') }}">Update_genepanel</a></li>
                        <li class="nav-item" id="navigation_help"><a class="nav-link {% if active_nav and active_nav == 'help' %}active{% endif %}" id="link_help" href="{{ url_for('blueprint_help.route_help') }}">Help</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main id="main"><div>
    {% block content %}{% endblock %}
</div></main>
    <script src="{{ url_for("static", filename="bootstrap/js/bootstrap.min.js") }}"></script>
</body>

</html>

gaps/templates/template_query_builder.html
{% extends "base_template.html" %}

{% block title %}GAPS query builder{% endblock %}

{% block head %}
    <script src="{{ url_for("static", filename="js/generic_functions.js") }}"></script>
    <script src="{{ url_for("static", filename="js/functions_query_builder.js") }}"></script>
{% endblock %}

{% block content %}
    <div class="container" id="page_query_builder">
        <div class="row gy-2 padding_below_section" id="row_informative_text">
            <div class="col-12" id="col_header">
                <h1 class="display-2" id="header">Query_builder</h1>
            </div>
            <div class="col-lg-9" id="col_text">
                <p id="paragraph_welcome">Welcome to the Query_builder! Your quest for finding new genes starts here. Use the three simple steps below to specify what you are looking for and press '<em>Search genes</em>' to start searching for new genes.</p>
                <p id="paragraph_help">For detailed information about every step in the query builder, and a step-by-step-guide, please refer to '<a href="{{ url_for('blueprint_help.route_help') }}#header_howto_query_builder" target="_blank"><em>How to use the query builder</em></a>' in the help-section.</p>
            </div>
        </div>
        <form id="input_form" class="gy-5" method="post" enctype="multipart/form-data" action="{{ url_for('blueprint_query_builder.query_builder') }}">
            <div class="row gy-5 gx-lg-5" id="row_query_symbols">
                <div class="col-lg-7 d-flex flex-column overflow-hidden" id="col_query_builder">
                    <h2 id="header_query_builder" class="section_header">1. Build a query</h2>
                    <div class="row gy-3" id="row_parameters">
                        <div class="col-12 col-xxl-auto" id="col_input_field"><label class="form-label" id="label_field" for="input_field">Field to search</label><select class="form-select" id="input_field">
                                <option value="AFFL">Affiliation</option>
                                <option value="ALL" selected="">All Fields</option>
                                <option value="AUTH">Author</option>
                                <option value="COLN">Author - Corporate</option>
                                <option value="FAUT">Author - First</option>
                                <option value="FULL">Author - Full</option>
                                <option value="AUID">Author - Identifier</option>
                                <option value="LAUT">Author - Last</option>
                                <option value="AUCL">Author Cluster ID</option>
                                <option value="BOOK">Book</option>
                                <option value="COIS">Conflict of Interest Statements</option>
                                <option value="DSO">DSO</option>
                                <option value="CDAT">Date - Completion</option>
                                <option value="CRDT">Date - Create</option>
                                <option value="EDAT">Date - Entrez</option>
                                <option value="MHDA">Date - MeSH</option>
                                <option value="MDAT">Date - Modification</option>
                                <option value="PDAT">Date - Publication</option>
                                <option value="ECNO">EC/RN Number</option>
                                <option value="ED">Editor</option>
                                <option value="EPDT">Electronic Publication Date</option>
                                <option value="EID">Extended PMID</option>
                                <option value="FILT">Filter</option>
                                <option value="GRNT">Grant Number</option>
                                <option value="ISBN">ISBN</option>
                                <option value="INVR">Investigator</option>
                                <option value="FINV">Investigator - Full</option>
                                <option value="ISS">Issue</option>
                                <option value="JOUR">Journal</option>
                                <option value="LANG">Language</option>
                                <option value="LID">Location ID</option>
                                <option value="MAJR">MeSH Major Topic</option>
                                <option value="SUBH">MeSH Subheading</option>
                                <option value="MESH">MeSH Terms</option>
                                <option value="OTRM">Other Term</option>
                                <option value="PAGE">Pagination</option>
                                <option value="PAPX">Pharmacological Action</option>
                                <option value="CNTY">Place of Publication</option>
                                <option value="PPDT">Print Publication Date</option>
                                <option value="PTYP">Publication Type</option>
                                <option value="PUBN">Publisher</option>
                                <option value="PID">Publisher ID</option>
                                <option value="SI">Secondary Source ID</option>
                                <option value="PS">Subject - Personal Name</option>
                                <option value="SUBS">Supplementary Concept</option>
                                <option value="WORD">Text Word</option>
                                <option value="TITL">Title</option>
                                <option value="TIAB">Title/Abstract</option>
                                <option value="TT">Transliterated Title</option>
                                <option value="UID">UID</option>
                                <option value="VOL">Volume</option>
                            </select></div>
                        <div class="col-12 col-sm-auto flex-grow-1" id="col_input_term"><label class="form-label" id="label_search_term" for="input_search_term">Search term</label><input class="form-control font-monospace" type="text" id="input_search_term" placeholder="e.g. Alzheimer" autocomplete="off"></div>
                        <div class="col-sm-auto flex-grow-1 flex-sm-grow-0" id="col_input_addition"><label class="form-label" id="label_search_term" for="input_add_type">Type of addition</label>
                            <div class="input-group flex-nowrap" id="input_group_add"><select class="form-select" id="input_add_type" disabled="">
                                    <option value="AND" selected="">AND</option>
                                    <option value="OR">OR</option>
                                    <option value="NOT">NOT</option>
                                </select><button class="btn btn-outline-primary" id="button_add_item" type="button">Add</button></div>
                        </div>
                    </div>
                    <div class="row d-flex flex-grow-1" id="row_generated_query">
                        <div class="col d-flex flex-column gy-3" id="col_generated_query"><label class="form-label" id="label_generated_query" for="input_generated_query">Query</label><textarea class="form-control d-flex flex-grow-1 textarea_minimal_height font-monospace" id="input_generated_query" spellcheck="false" autocomplete="off" placeholder="No query found" style="min-height: 93px;" name="input_generated_query"></textarea><small class="form-text" id="help_query">Or, write/paste your own query</small></div>
                    </div>
                </div>
                <div class="col-lg-5" id="col_specify_symbols">
                    <h2 id="header_specify_symbols" class="section_header">2. Specify gene symbols</h2>
                    <div class="row gy-3" id="row_specify_symbols">
                        <div class="col" id="col_include_exclude_symbols"><label class="form-label" id="label_inlude_exclude_symbols">Include or exclude gene symbols from search</label>
                            <div class="form-check" id="radio_label_include_symbols"><input class="form-check-input" type="radio" id="radio_include_symbols" name="radio_include_symbols" value="true" checked=""><label class="form-check-label" id="label_include_label" for="radio_include_symbols">Include gene symbols</label></div>
                            <div class="form-check" id="radio_label_exclude_symbols"><input class="form-check-input" type="radio" id="radio_exclude_symbols" name="radio_include_symbols" value="false"><label class="form-check-label" id="label_exclude_symbols" for="radio_exclude_symbols">Exclude gene symbols</label></div>
                        </div>
                        <div class="col-lg-12" id="col_display_symbols"><label class="form-label" id="label_symbols" for="input_symbols">Gene symbols to include/exclude</label><textarea class="form-control textarea_minimal_height font-monospace" id="input_symbols" autocomplete="off" spellcheck="false" placeholder="No gene symbols specified" style="min-height: 93px;" name="input_symbols"></textarea><small class="form-text" id="help_multiple_symbols">Separate gene symbols with a comma-sign (,)</small></div>
                        <div class="col" id="col_load_symbols"><label class="form-label" id="label_load_symbols" for="input_load_symbols">Or, load gene symbols from a file</label>
                            <div class="input-group" id="input_group_clear_file"><input class="form-control" type="file" id="input_load_symbols" name="input_load_symbols" accept=".txt, .csv, .tsv"><button class="btn btn-outline-primary" id="button_clear_file" type="button">Clear</button></div><small class="form-text">Only files with one gene symbol per line are accepted with a size limit of 10 MB</small>
                        </div>
                    </div>
                </div>
                <div class="col-12" id="col_options">
                    <h2 id="header_options" class="section_header">3. Optional options</h2>
                    <div class="row gy-3" id="row_date_options">
                        <div class="col text-nowrap" id="row_date_after"><label class="form-label" id="label_date_after" for="input_date_after">Search articles published after date</label><input class="form-control" id="input_date_after" type="date" name="input_date_after"></div>
                        <div class="col text-nowrap" id="row_date_before"><label class="form-label" id="label_date_before" for="input_date_before">Search articles published before date</label><input class="form-control" id="input_date_before" type="date" name="input_date_before"></div>
                    </div>
                </div>
                <div class="col" id="col_submit_options">
                    <div id="alert_box"></div>
                    <div class="row gy-3" id="row_submit_options">
                        <div class="col-auto d-flex align-items-center" id="col_new_tab">
                            <div id="div_new_tab" class="form-check form-switch"><input type="checkbox" id="check_new_tab" class="form-check-input"><label class="form-label text-nowrap form-check-label my-0" id="label_new_tab" for="check_new_tab">Open search in new tab</label></div>
                        </div>
                        <div class="col-sm-1 gy-0 gx-0" id="col_spacer_submit_reset_0">
                            <div id="spacer_submit_reset_0"></div>
                        </div>
                        <div class="col-sm-12 col-md-auto flex-grow-0 d-grid" id="col_clear"><button class="btn btn-outline-danger text-nowrap" id="button_clear" type="reset">Clear all input</button></div>
                        <div class="col-sm-1 gy-0 gx-0" id="col_spacer_submit_reset_1">
                            <div id="spacer_submit_reset_1"></div>
                        </div>
                        <div class="col-sm-12 col-md-auto d-grid" id="col_submit"><button class="btn btn-primary text-nowrap" id="button_submit" type="submit"><span class="spinner-border spinner-border-sm gx-2" role="status" id="spinner_submit_button" hidden=""></span><span id="text_submit_button">Search genes<br></span></button></div>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

gaps/templates/template_update_genepanel.html
{% extends "base_template.html" %}

{% block title %}GAPS update genepanel{% endblock %}

{% block head %}
    <script src="{{ url_for("static", filename="js/generic_functions.js") }}"></script>
    <script src="{{ url_for("static", filename="js/functions_update_genepanel.js") }}"></script>
{% endblock %}

{% block content %}
    <div class="container" id="page_update_genepanel">
        <div class="row gy-2 padding_below_section" id="row_informative_text">
            <div class="col-12" id="col_header">
                <h1 class="display-2" id="header">Update_genepanel</h1>
            </div>
            <div class="col-lg-9" id="col_text">
                <p id="paragraph_information">This is the page where genepanels are updated. By uploading a genepanel to GAPS, some additional options and filters will be unlocked for the results of searches. Example: options to hide all genes from a search that are already included in a genepanel.</p>
                <p id="paragraph_help">For information about how to update genepanels and which files are accepted for uploads, please refer to '<a href="{{ url_for('blueprint_help.route_help') }}#header_howto_update_genepanel" target="_blank"><em>How to update a genepanel</em></a>' in the help-section.</p>
                <div class="alert alert-info" role="alert" id="alert_best_results"><span id="text_alert_best_results"><strong>Important!&nbsp;</strong>To achieve the best results, when using the extra options and filters, it is important to keep uploading new versions of genepanels to make use of the newest information in genepanels.<br></span></div>
            </div>
        </div>
        <form id="form_update_genepanel" class="padding_below_section" method="post" enctype="multipart/form-data" action="{{ url_for('blueprint_api.update_genepanel_submit') }}">
            <h2 id="header_update_genepanel" class="section_header">Update genepanel</h2>
            <div class="col-lg-10" id="col_update_genepanel">
                <div id="alert_box"></div>
                <div class="row gy-3" id="row_update_genepanel">
                    <div class="col" id="col_select_genepanel"><label class="form-label" id="label_upload_genepanel" for="input_upload_panel">Select a genepanel</label>
                        <div class="input-group" id="input_group_upload_genepanel"><input class="form-control" type="file" id="input_upload_genepanel" required="" name="input_upload_genepanel" accept=".txt, .csv, .tsv"><button class="btn btn-outline-primary" id="button_clear" type="button">Clear</button></div><small class="form-text" id="help_accepted_files">Only tab-separated-files (TSV-files) up to 10 MB in size are accepted</small>
                    </div>
                    <div class="col-lg-auto align-self-start d-grid" id="col_update_genepanel"><label class="form-label" id="label_update_genepanel" for="button_update_genepanel">Update genepanel</label><button class="btn btn-primary" id="button_update_genepanel" type="submit"><span class="spinner-border spinner-border-sm" role="status" id="spinner_submit_button" hidden=""></span><span id="text_submit_button">Upload &amp; update genepanel<br></span></button></div>
                </div>
            </div>
        </form>
        <div class="row section_header" id="row_statistics">
            <div class="col-lg-9" id="col_statistics">
                <h2 id="header_statistics" class="section_header">Statistics</h2>
                <p id="paragraph_about_statistics">Below are a few fun statistics about genepanels that have been uploaded before. Statistics about searches are not included here.</p>
                <p id="paragraph_statistics">Unique genes: {% if unique_genes %}{{ unique_genes }}{% else %}not available{% endif %}<br>Unique aliases: {% if unique_aliases %}{{ unique_aliases }}{% else %}not available{% endif %}<br>Unique genepanels: {% if unique_genepanels %}{{ unique_genepanels }}{% else %}not available{% endif %}<br><br></p>
            </div>
        </div>
    </div>
{% endblock %}